### ISSUE TITLE
2019-08-12.md

### ISSUE THREAD

**Issue by tianlmn** [CtripFE/fe-weekly#125]

**Comment by Yunin** [comment]
#### [页面可视化搭建工具技术要点](http://www.alloyteam.com/2019/07/h5-build-tool-pipeline/)

本文讨论了活动页面开发的痛点, 总结出页可视化搭建工具的 7 个技术要点和 4 个技术难点, 并整理出理想的运营页面可视化搭建工具。
#### [营销活动设计的数据驱动](https://www.yuque.com/gkx5p8/xiy9bn/qecgbv)

本文主要提供了一些在设计层面数据驱动的思维框架与思考方法，可能还有很多不足，但是我们会不断进行完善，让这个方式更简单易用，切实的能帮助更多的设计师有理有据的做设计。
#### [rocketmq一个不消费问题排查](http://www.jiangxinlingdu.com/rocketmq/2019/08/06/noconsumer.html)

commitlog的文件序号错误，导致新生产的比老的小（2对应的文件序号比1的小），导致doReput一直操作不到数据，导致ConsumeQueue没数据进来，导致发送的可以正常发送，并且提升send_ok，并且通过message_id可以查询到数据，但是消费端就是消费不到数据。

**Comment by mirreal** [comment]
#### [How Does the Development Mode Work?](https://overreacted.io/how-does-the-development-mode-work/)

为什么需要区分开发模式与生产模式，以及如何更合理地利用规则进行优化。

**Comment by Hental** [comment]
### [抖音研发实践：基于二进制文件重排的解决方案 APP启动速度提升超15% ](https://mp.weixin.qq.com/s/Drmmx5JtjG3UtTFksL6Q8Q)

通过重排二进制文件，减少 Page Fault，获得了约 15 % 的启动时间减少。

### [JavaScrip中的“观察者模式”](https://zhuanlan.zhihu.com/p/76039838)

JavaScript 中存在大量的异步场景，非常适合“观察者模式”，[RxJS](https://cn.rx.js.org/) 便是基于观察者模式。

### [Do React Hooks Replace Redux?](https://medium.com/javascript-scene/do-react-hooks-replace-redux-210bab340672)

React Hooks 是个好东西，但是它只能管理组件的 state，而 Redux 是管理整个应用的 state。

**Comment by BetaMee** [comment]
#### [ Serverless For Frontend 前世今生](https://mp.weixin.qq.com/s/xxtLIIHzO6EqQKxMNTPwvA)

 Serverless For Frontend 似乎对于大公司的技术生产力有着直接有效的提升，但对于个人开发者来说，
只需要写几个 Function 就可以完成任务了，那个人的成长价值在哪呢？

#### [让自动化工作流解放你的双手](https://mp.weixin.qq.com/s/MJX5pVwugKsRO__fjhPVmg)

一篇讲解如何使用 jenkins 执行自动化工作流的教程。

#### [组织架构与中台建设，回顾阿里等四大商业巨头的战略变迁](https://mp.weixin.qq.com/s/RTrYFZhBloS4nnsQFPNUbg)

商业的变迁带来组织架构的进化，而正是在这些组织架构的变化中，才能推动技术结合业务的落地。技术人员要学会从商业变化中找到技术价值。

**Comment by tianlmn** [comment]
### [不止于 CSS](https://github.com/chokcoco/iCSS)

css入门容易精通难，推荐一个学习css的github账号。

### [大揭秘！“恐怖”的阿里一面，我究竟想问什么](https://juejin.im/post/5d4cd42a6fb9a06aea618155)

工作积累和学习积累都很重要，剩下的就看运气了。

### [你未必知道的49个CSS知识点](https://juejin.im/post/5d3eca78e51d4561cb5dde12)

css差缺补漏。
