### ISSUE TITLE
2019-09-09.md

### ISSUE THREAD

**Issue by tianlmn** [CtripFE/fe-weekly#129]

**Comment by Yunin** [comment]
#### [依赖孪生：低成本的依赖安全方案](https://www.phodal.com/blog/dependency-twins/)
 依赖孪生——针对于中小型 IT 组织的依赖方案。
 #### [什么时候需要进行代码重构？](https://juejin.im/post/5d6695f051882554e26201d2)
 重构的关键在于 运用大量微小且保持软件行为的步骤，一步步达成大规模的修改。
 #### [Hello! Umi UI](https://github.com/sorrycc/blog/issues/86)
Umi UI 的第一个版本终于上了。🌹 🌹 🌹
#### [使用 JMeter 进行 Dubbo 性能测试](https://www.cnkirito.moe/dubbo-perf-benchmark/)
介绍了使用 JMeter 压测 HTTP 的方法，熟悉 JMeter 的使用方式，并着重介绍了使用 jmeter-plugins-for-apache-dubbo 插件压测 Dubbo 的方法。
#### [华为云 TaurusDB 性能挑战赛赛题总结](https://www.cnkirito.moe/taurusdb-race/)
比赛整体分成了初赛和复赛两个部分，初赛要求实现一个简化、高效的本地 kv 存储引擎，复赛在初赛的基础上增加了计算存储分离的架构，计算节点需要通过网络传输将数据递交给存储节点存储。

**Comment by Hental** [comment]
### [VSCode原理解析 - 断点调试 ](https://fed.taobao.org/blog/2019/08/15/vscode-debug-source-analyse/)

类似 Language Server Protocol, vscode 通过 DAP(Debug Adapter Protocol) 协议，支持对不同的语言进行 debug。

### [The story of a V8 performance cliff in React](https://v8.dev/blog/react-cliff)

React 在新的 Profile Devtool 中使用了大量的小数点记录性能时间，导致 v8 变得很慢。

### [微软提出 CSS Modules V1 ：通过 import 语句将 CSS 模块导入到组件中](https://www.infoq.cn/article/tfu5VFMYSxt89KOLNLp6)

在 ES module 直接引入 css，并作为一个 CSSStyleSheet 对象，极大的方便了组件的开发。

**Comment by BetaMee** [comment]
#### [面试分享：两年工作经验成功面试阿里P6总结](https://juejin.im/post/5d690c726fb9a06b155dd40d)

前端两年工作经验的面试基本面，看看自己能不达到这样的水平。

#### [深入理解图片和框架的原生懒加载功能](https://mp.weixin.qq.com/s/9zQv2ntL8JuJVk694zEEZQ)

使用原生 HTML  loading 特性来实现懒加载

#### [美团点评的Service Mesh实践及落地难点解析](https://mp.weixin.qq.com/s/iEHR7rtsswUqiWcvOhhzDQ)

关于新一代微服务架构 Service Mesh 的实践经验

**Comment by tianlmn** [comment]
### [京东 PC 首页 2019 改版前端总结](https://juejin.im/post/5d71c98a6fb9a06ae8362f52)

京东PC端的首页改版的一些经验分享，主要是加入了强类型、骨架屏等。

### [如何写出一个惊艳面试官的深拷贝?](https://juejin.im/post/5d6aa4f96fb9a06b112ad5b1)

你确定你能写出一个没有bug的深拷贝吗？

### [深入理解Node.js 中的进程与线程](https://juejin.im/post/5d43017be51d4561f40adcf9)

文章除了介绍概念，通过Node.js 的角度讲解进程与线程，并且讲解一些在项目中的实战的应用
