### ISSUE TITLE
AMP && PWA 实践分享

### ISSUE THREAD

**Issue by elevenbeans** [CtripFE/fe-weekly#49]
#### 如题

@StevenX911 

有看到我们公共前端这边投入了不少的资源在做 AMP/PWA 的落地。

从掘金随手搬运两篇高 Star 的文章：

+ 大搜车无线团队： [什么是 PWA？](https://juejin.im/post/5a9e8ad5f265da23a40456d4)
+ 饿了么：[饿了么的 PWA 升级实践](https://juejin.im/post/58dba0b3a22b9d00647db6c3)

在条件成熟的时候，我们周刊里面是不是也可以做类似的原创总结文章，或者跨团队的分享等等。

希望会有人认领一下这个 issue  ：）

**Comment by StevenX911** [comment]
@elevenbeans 目前还在做AMP的落地，后续会做分享

**Comment by elevenbeans** [comment]
[What Google AMP means for the JavaScript community
](https://molily.de/amp/)
