### ISSUE TITLE
前端面试到底该问些什么问题？

### ISSUE THREAD

**Issue by StevenX911** [CtripFE/fe-weekly#5]
之前比较关注大家对Javascript基础的掌握，比如原型、闭包、作用域、垃圾回收等，另外还会夹杂一些对HTML和CSS的掌握情况的摸底，现在由于Node的流行，开始要求前端工程师掌握HTTP协议，文件I/O，服务端渲染，SEO等，不知道大家有什么看法？

**Comment by CurtisCBS** [comment]
* 前端优化

**Comment by StevenX911** [comment]
@CurtisCBS 具体呢？

**Comment by StevenX911** [comment]
- https://github.com/hawx1993/Front-end-Interview-questions
- https://github.com/h5bp/Front-end-Developer-Interview-Questions/tree/master/Translations/Chinese#network-questions

**Comment by RayJune** [comment]
感觉根据项目去一步步深究是一个不错的选择

P.S. 携程笔试的最早，但先收到了 BAT 的面试通知，还在等待携程的笔试改卷中，期待 ing :>
