### ISSUE TITLE
往期文章分类名去重的说明

### ISSUE THREAD

**Issue by sturloly** [CtripFE/fe-weekly#7]
经查询至今各期有如下分类名：

业界动态
前端技术
实用技巧
程序人生
技术纵横
团队分享
前端开发（重复，’技术‘优于’开发‘，建议不再实用）
实用推荐（重复，’技巧优于‘推荐’，建议不再实用）

请后续使用此issue中，已经归档的分类名，或在此申明新的分类名，然后使用。

**Comment by mirreal** [comment]
这是我对栏目的简单定义，以及分类标准：

https://github.com/CtripFE/fe-weekly#周刊格式

结合这份样刊：https://github.com/CtripFE/fe-weekly/blob/master/example.md

应该还算明确

**Comment by stoneyong** [comment]
关于 “团队分享” 的分类， 是否需要讨论下 ？ 
个人感觉  文章的分类都是按照文章的内容性质分类的，团队分享是 按照作者分类的， 会出现文章错位的感觉。
建议：  为了突出是我们团队的分享  ， 可以在文章的介绍末尾备注下，  例如：（注：@XX 作）   或者 以一个别样的格式 ，再在周刊 末尾说明 。

**Comment by mirreal** [comment]
@stoneyong 是的，可以对这部分做一些强调

**Comment by stoneyong** [comment]
@mirreal  我的意思是 团队分享 这个分类是否可以去除， 还是按照文章性质分类， 团队贡献的文章 采用强调的方式标注。
